### ISSUE TITLE
Any alternative with JSON ?

### ISSUE THREAD

**Issue by blackrek** [xmlcalendar/data#11]
Any alternative with JSON ?

**Comment by xmlcalendar** [comment]
Hi, We do not have a calendar in json format yet, but I think that we can implement a converter for xml to json, so what format do you want to suggest?

**Comment by blackrek** [comment]
thank you for your interest.
I think the exact format does not matter.
I can offer such an example for february and march of 2017:

```
{
	"years": [{
		"year": 2017,
		"months": [{
			"month": 2,
			"days": [{
				"day": 22,
				"type": 2
			},
			{
				"day": 23,
				"type": 3
			},
			{
				"day": 24,
				"type": 3
			}]
		},
		{
			"month": 3,
			"days": [{
				"day": 7,
				"type": 2
			},
			{
				"day": 8,
				"type": 3
			}]
		}]
	}]
}
```
or a shorter version
```
[{
	"2017": [{
		"2": [{
			"22": 2
		},
		{
			"23": 3
		}]
	},
	{
		"3": [{
			"7": 2
		},
		{
			"8": 3
		}]
	}]
}]
```

**Comment by xmlcalendar** [comment]
I added json format:
20* is a short day
`
{
  "year": 2021,
  "months": [
    {
      "month": 1,
      "days": "1,2,3,4,5,6,7,8,9,10,16,17,23,24,30,31"
    },
    {
      "month": 2,
      "days": "6,7,13,14,20*,21,22,23,27,28"
    },
`
example: http://xmlcalendar.ru/data/ru/2021/calendar.json

**Comment by xmlcalendar** [comment]
You can also use http://xmlcalendar.ru/data/ru/all/calendar.json
for all years
