### ISSUE TITLE
Обновление календаря

### ISSUE THREAD

**Issue by sobolev-vodopad** [xmlcalendar/data#15]
Добрый день. Спасибо за сервис!

Какого числа происходит обновление календаря в новом году, чтобы можно было в автоматическом режиме его обновлять у себя?

**Comment by Kniazeff** [comment]
Конкретной даты нет, ближе к концу года появляется следующий.
Адрес актуальных данных http://xmlcalendar.ru/data/ru/2019/calendar.xml, подставляйте в путь значение текущего года.
