### ISSUE TITLE
22 апреля 2020 - внеплановый выходной

### ISSUE THREAD

**Issue by Bounz** [xmlcalendar/data#21]
Приветствую!
Спасибо за полезный проект!

В связи с последними событиями и назначением 22 апреля 2020 днем общероссийского голосования по поправкам к Конституции, который будет оплачиваемым выходным днем - стоит ли добавить его в календарь выходных на этот год?

Новость: https://ria.ru/20200228/1565304896.html

**Comment by xmlcalendar** [comment]
Да стоит, если этот день будет выходным. Пока это только на словах. Необходимы подтверждающие документы.

**Comment by Bounz** [comment]
По 22 апреля есть Указ Президента РФ https://www.consultant.ru/document/cons_doc_LAW_347817/
Но теперь его должны перенести.

Однако теперь неделя с 30 марта по 3 апреля должна быть нерабочей (Указ Президента http://publication.pravo.gov.ru/Document/View/0001202003250021)
