### ISSUE TITLE
Нерабочие дни 24 июня и 1 июля 2020 г.

### ISSUE THREAD

**Issue by Bounz** [xmlcalendar/data#27]
Приветствую!

Этот год не будет простым в плане работы с выходными и "нерабочими" днями 🙂 
Можете посмотреть PR #26 на основе Указов Президента №345 от 29.05.2020 и №354 от 01.06.2020?

@xmlcalendar, @lazar2606

**Comment by xmlcalendar** [comment]
Спасибо, готово
