### ISSUE TITLE
Календарь на 2021 год

### ISSUE THREAD

**Issue by frostbtn** [xmlcalendar/data#28]
Как я понимаю, постановление о переносе выходных на 2021 год еще не принято, но вроде бы уже должно быть скоро. Это issue создано, чтобы на него можно было подписаться и загрузить календарь, как только он появится. Не забудьте только, пожалуйста, закрыть это issue как только "кастанёте" свою могущественную магию.
Спасибо, что занимаетесь этим -- незаменимая помощь!

**Comment by agladysh** [comment]
NB: вот есть такая интересная ссылочка: https://data.gov.ru/opendata/7708660670-proizvcalendar, до 2025.

**Comment by frostbtn** [comment]
О, появился календарь на 2021. Отлично!
