### ISSUE TITLE
лежит сайт

### ISSUE THREAD

**Issue by lowercase** [xmlcalendar/data#35]
Поднимите, пожалуйста, http://xmlcalendar.ru. Шэф, усе пропало

**Comment by xmlcalendar** [comment]
Добавлен новый репозиторий с зеркалом сайта, так что можно использовать домен xmlcalendar.github.io если xmlcalendar.ru недоступен

Пример:
https://xmlcalendar.github.io/data/ru/2023/calendar.xml
https://xmlcalendar.github.io/data/ru/all/calendar.txt
