### ISSUE TITLE
Hackers Scrypt Injection

### ISSUE THREAD

**Issue by slauter77** [xmlcalendar/data#51]
Добрый день!
Если скачать XML файл за 2020 год на сайте http://xmlcalendar.ru/ (для России) то в конце файла прикреплен скрипт как явная попытка сделать что-то нехорошее. Он обфусцирован, но беглый просмотр выявил название криптовалют и кошельков.
Что ОН здесь делает????

**Comment by xmlcalendar** [comment]
Добрый день, спасибо что написали. Проблем не выявлено, файлы в норме. Думаю причина в прокси сервисе на вашей стороне. Попробуйте загрузить файл через https://xmlcalendar.ru

**Comment by slauter77** [comment]
Спасибо за быстрый ответ! Вы оказались правы: файлы календаря в порядке, а проблемы похоже на моей стороне.
